#!/bin/bash
#PBS -l partition=gpu
#PBS -l nodes=1:ppn=9:gpus=1:skylake
#PBS -l walltime=1:00:00
#PBS -N wikiann_ht_ner_test_xlmr
#PBS -l pmem=5gb
#PBS -m ae
#PBS -M kushaljayesh.tatariya@kuleuven.be
#PBS -A default_project

source activate creole

codebase=/data/leuven/351/vsc35188/machamp
loggingdir=/data/leuven/351/vsc35188/creole-nlp/CreoleNLP-Baselines/creole-dro

cd $loggingdir

bert='xlmr'
algo='baseline'
lang='wikiann_ht'
task='ner'

#assumes only one
serialized_dir_a=$loggingdir/logs/$lang-$task-$bert-$algo/

input_file='data/WikiAnn_data/ht/ht-test.txt'
output_file=$serialized_dir_a/test.pred.tsv

python $codebase/predict.py $serialized_dir_a/2022.12.13_20.01.25/model.pt $input_file $output_file --device 0 
