#!/bin/bash
#PBS -l partition=gpu
#PBS -l nodes=1:ppn=9:gpus=1:skylake
#PBS -l walltime=1:00:00
#PBS -N wikiann_pih_ner_test_mbert
#PBS -l pmem=5gb
#PBS -m ae
#PBS -M kushaljayesh.tatariya@kuleuven.be
#PBS -A default_project

source activate creole

codebase=/data/leuven/351/vsc35188/machamp
loggingdir=/scratch/leuven/351/vsc35188/CreoleNLP-Baselines/creole-dro

cd $loggingdir

bert='mbert'
algo='baseline'
lang='wikiann_pih'
task='ner'

serialized_dir_a=$loggingdir/logs/$lang-$task-$bert-$algo

input_file='data/WikiAnn_data/pih/pih-test.txt'
output_file=$serialized_dir_a/test.pred.tsv

python $codebase/predict.py $serialized_dir_a/2022.12.16_11.28.28/model.pt $input_file $output_file --device 0 
