#!/bin/bash
#PBS -l partition=gpu
#PBS -l nodes=1:ppn=9:gpus=1:skylake
#PBS -l walltime=1:00:00
#PBS -N singlish_upos_test_xlmr
#PBS -l pmem=5gb
#PBS -m ae
#PBS -M kushaljayesh.tatariya@kuleuven.be
#PBS -A default_project

source activate creole

codebase=/data/leuven/351/vsc35188/creole-nlp/machamp
loggingdir=/data/leuven/351/vsc35188/creole-nlp/creole-dro

cd $loggingdir

bert='xlmr'
algo='baseline'
lang='singlish'
task='upos'

#assumes only one
serialized_dir_a=$loggingdir/logs/$lang-$task-$bert-$algo/

if [[ $task == "upos" ]]
then
    if [[ $lang == "singlish" ]]
        then
            input_file='data/test/singlish/test.conll'
        else
            input_file='data/test/naija/naija-sud/pcm_nsc-ud-test.conllu'
        fi
    output_file=$serialized_dir_a/test.pred.conll
else
    input_file='data/test/naija/masakhane-ner-pcm/test.txt'
    output_file=$serialized_dir_a/test.pred.txt
fi

python $codebase/predict.py $serialized_dir_a/2022.11.24_22.17.31/model.pt $input_file $output_file --device 0 
