#!/bin/bash
#PBS -l partition=gpu
#PBS -l nodes=1:ppn=9:gpus=1:skylake
#PBS -l walltime=1:00:00
#PBS -N jamaican_nli_test_mbert
#PBS -l pmem=5gb
#PBS -m ae
#PBS -M kushaljayesh.tatariya@kuleuven.be
#PBS -A default_project

source activate creole

codebase=/data/leuven/351/vsc35188/machamp
loggingdir=/scratch/leuven/351/vsc35188/CreoleNLP-Baselines/creole-dro

cd $loggingdir

serialized_dir_a=$loggingdir/logs/nli_jamaican_mbert_finetuned

input_file='data/jam-nli-data/jamnli-test.tsv'
output_file=$serialized_dir_a/test.pred.tsv

python $codebase/predict.py $serialized_dir_a/2023.01.03_11.43.17/model.pt $input_file $output_file --device 0 
